[project]
name = "znamutils"
authors = [{name = "Antonin Blot", email= "antonin.blot@crick.ac.uk"}]
description = "Common utility functions for analysis"
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["version"]
dependencies = ["decopatch", "makefun", "decorator"]
license = {text = "MIT"}

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["znamutils*"]
exclude = ["tests", "docs*"]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "coverage",
  "mypy",
  "numpy",
  "pre-commit",
  "ruff",
  "setuptools_scm",
]

[tool.pytest.ini_options]
addopts = "--cov=znamutils"

[tool.setuptools_scm]

[tool.ruff]
line-length = 88
exclude = ["__init__.py","build",".eggs"]
fix = true

[tool.ruff.lint]
select = ["I", "E", "F"]
